spring:
  messages:
    basename: messages, errors # messages가 기본설정임

server:
  servlet:
    session:
      tracking-modes: cookie # cookie, url, ssl

logging:
  level:
    org:
      apache:
        coyote:
#          http11: DEBUG
